### ISSUE TITLE
Add Power Consumption into Utility Meter 

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#113]

**Comment by JamesMcCarthy79** [comment]
done

**Comment by AaronArgent** [comment]
What did you use for power consumption monitoring?

**Comment by JamesMcCarthy79** [comment]
@AaronArgent I used a number of methods to monitor power.

1. Smart plugs to monitor appliance consumption.

2. IOTAWatt to monitor total consumption and those with high current draw like ovens and air conditioners

3. I use the Utility meter component to monitor time in hours for a given period then a template sensor for converting it into kWh based on its average consumption.

I am writing a blog post about this topic as I have had a few questions around how i did it I will share on my github when its ready.
