### ISSUE TITLE
Day before (trash/recycle) to use with automation reminder

### ISSUE THREAD

**Issue by itajackass** [JamesMcCarthy79/Home-Assistant-Config#114]
Hi, i read all your code but i don't understand what is the sensor variable you use to set the day for reminder ONE DAY before the trash is picked up by trash-veicle.

For example if the trash pickup day is 2019-03-15...then the trash day reminder must be 2019-03-14.....i don't understand where you set it.. 

I think here:
# Recycle - Pickup schedule is every other week.
## Set the day to a day before the actual day leaving time for reminders

But from your code i don't undestand where you compare (pickup day minus 1day) with today... Where do you calculate pickupday minus 1 day?

**Comment by JamesMcCarthy79** [comment]
Hi to set the trash or recycle day you need to set the input select you created to the day before trash or recycle day.

![image](https://user-images.githubusercontent.com/34696670/54517342-20cd3500-49ad-11e9-9d20-e487592b7b7a.png)

 You can also add these to the front end but unless they change then you really only need to set them up once.

**Comment by itajackass** [comment]
Hi, so probably is a traslation problem in italian or misunderstanding... Let me know:

Pickup day is the day when I have to carry out the trash for tomorrow.... or pickup day is the day when the council vehicle come to get trash in my street?

**Comment by MZorzy** [comment]
@itajackass  if in your town pick up trash in the (too early ;-) ) morning i think the best way is set an apposite (google/other) calendar with some "domani raccolgono secco" (tomorrow pigkup ...)
time start day before in the afternoon when home and can see/ put out trash
time end 23:59.
 with google calendar you can also delete/move scheduled holiday without trash's pikup

**Comment by itajackass** [comment]
@mzorzy why not set input_select as day of effective town pickup day.... And in the automation for notification check if today == pickup_day minus 1 day? Is it not more clear?

**Comment by JamesMcCarthy79** [comment]
I set my notification for the day before so I can then set a notification before I go to bed to remind me to take out the bins. I use Node-RED for my automations so have set it up to watch my calendar for changes to my schedule.
