### ISSUE TITLE
move Notify off Pushbullet

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#122]
I am having troubles with pushbullet notifications showing on my android phone due to permissions the notifications are there I just have to check the app to get them which defeats the purpose.

Looking for alternatives for notification on Android maybe this [Ariela](https://community.home-assistant.io/t/ariela-home-assistant-android-client-updates-thread/91264)

or [Actionable Notifications](https://community.home-assistant.io/t/android-actionable-notifications/65347)

**Comment by JamesMcCarthy79** [comment]
[Telegram Bot](https://community.home-assistant.io/t/howto-setting-up-a-telegram-bot-for-all-your-home-automation-messages/63085) Looks like a goer

[Red Bot](https://github.com/guidone/node-red-contrib-chatbot) for Node-RED

**Comment by snis** [comment]
+1 for Telegram

**Comment by JamesMcCarthy79** [comment]
I'm using Ariela for now which is working well enough for now.
