### ISSUE TITLE
What is "Spray Suitability"

### ISSUE THREAD

**Issue by johntdyer** [JamesMcCarthy79/Home-Assistant-Config#128]
So I am trying to understand what exactly this automation is doing... What is "Spraying" to you :)

**Comment by JamesMcCarthy79** [comment]
@johntdyer So you have stumbled upon some code I use for my new climate garden irrigation lovelace tab.

In short I have automated garden watering I also run a fertilizer program where I run water with fert (spraying) for x amount of time and then run with just water for another 20 mins to flush the lines.

Fert can be expensive so I don't want to waste it hence the Spraying Condition metric I use. Basically there is a calculation used with the Delta T to calculate ideal spraying conditions it takes into account that its not too cold or dewy where the fert would hit the leaf and roll off and not too hot where the fert would evaporate in the air before getting to the plants. I also take into account wind speed and current rain conditions.  I haven't released the dashboard to the community yet as I need to do some hardcore maths formulas for calculating Evoptranspiration but once finished I'll do a complete write up. 

Sneak Peak
![image](https://user-images.githubusercontent.com/34696670/57675844-6bde8e00-7666-11e9-9b31-7d5b3978a9ff.png)

**Comment by nickdaria** [comment]
Jesus that’s awesome. I take it you use Node-Red for the calculations?

**Comment by JamesMcCarthy79** [comment]
> Jesus that’s awesome. I take it you use Node-Red for the calculations?

Thanks man, calculations are done via python script but could also be done with Node-RED
