### ISSUE TITLE
Restart time sensor

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [JamesMcCarthy79/Home-Assistant-Config#129]
Hey, great config, thanks!

I can't seem to find your sensor config to get the restart time, could you give me a pointer?

**Comment by JamesMcCarthy79** [comment]
Hey, this is a recent addition so isn't yet documented. I use Node-RED flow that counts the time between messages. Home Assistant has a boolean called `homeassistant.homeAssistant.isConnected`
I monitor this and the time between its state changes I then send the payload value to HA via MQTT.

![image](https://user-images.githubusercontent.com/34696670/58168407-89000600-7cd1-11e9-9117-cd5f6bb6226d.png)

**Comment by WaaromZoMoeilijk** [comment]
Awesome thanks. Do you mind sharing the node red flow?

Kind regards / Met vriendelijke groet,

Ezra Holm

**Comment by JamesMcCarthy79** [comment]
Sure thing here you go just replace the details for your broker.

You will need to install the Interval Time Node `"npm install node-red-contrib-interval-length"`

![image](https://user-images.githubusercontent.com/34696670/58211963-aa440f00-7d30-11e9-9e46-71cd427a5ec2.png)


`[{"id":"a7f4ddda.33c14","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"c768c45c.d1c9f8","type":"inject","z":"a7f4ddda.33c14","name":"HASS Connected?","topic":"","payload":"homeassistant.homeAssistant.isConnected","payloadType":"global","repeat":"1","crontab":"","once":false,"onceDelay":0.1,"x":540,"y":260,"wires":[["9c000c44.90797"]]},{"id":"9c000c44.90797","type":"rbe","z":"a7f4ddda.33c14","name":"","func":"rbe","gap":"","start":"","inout":"out","property":"payload","x":750,"y":220,"wires":[["f2c7a353.6bc61"]]},{"id":"f2c7a353.6bc61","type":"interval-length","z":"a7f4ddda.33c14","format":"human","bytopic":false,"minimum":"10","maximum":"","window":"","timeout":false,"msgTimeout":"0","minimumunit":"secs","maximumunit":"msecs","windowunit":"msecs","msgTimeoutUnit":"msecs","reset":false,"startup":false,"msgField":"payload","timestampField":"timestamp","repeatTimeout":false,"name":"Restart Time","x":790,"y":320,"wires":[["72d40438.b464dc"],[]]},{"id":"72d40438.b464dc","type":"mqtt out","z":"a7f4ddda.33c14","name":"","topic":"harestart","qos":"","retain":"","broker":"1f0ce342.96db4d","x":780,"y":480,"wires":[]},{"id":"1f0ce342.96db4d","type":"mqtt-broker","z":"","name":"MQTT Broker","broker":"0.0.0.0","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]`

**Comment by WaaromZoMoeilijk** [comment]
Thank you sir, great config, adapted quite some things. 

Kind regards 

Ezra
