### ISSUE TITLE
Move Colour LED Spotify Sync to Node-RED

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#130]
I used to have my led strips sync colour with Spotify Album artwork but it hasn't worked since I moved off App Deamon. I can do it with Node-RED just need a reminder like this right here will this a crack tonight.

**Comment by JamesMcCarthy79** [comment]
Installed colorthief library will perform some testing tonight.

**Alexa Media Player**
- [x] Spotify Album Colour

**Kodi Media Player**
- [x] Album Artwork
- [x] Music Video Artwork
- [x] TV Show Poster
- [x] Movie Poster

**Comment by JamesMcCarthy79** [comment]
This is completed for playing spotify on Amazon Echo through the media_player component. Was a bit of mucking about but I have LED lights syncing to album artwork for the win. Next to tackle the same for Kodi music, tv and movie posters.

![image](https://user-images.githubusercontent.com/34696670/59896868-9c67d380-942d-11e9-990e-f7c1df20b0a1.png)

**Comment by JamesMcCarthy79** [comment]
Sorted for Kodi also as it uses the same component.

**Comment by MrThiemann** [comment]
can you share your *.json-code ? for example the first two nodes I don't know which ones they are. Thank you =)
