### ISSUE TITLE
Install Fitbit Component

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#133]
Need to update to HA 0.94.0 in order for this to work a little bit of work for me to be able to update to this version just yet.

**Comment by JamesMcCarthy79** [comment]
This will not auth me at all anyone who has been able to enable this component I'd love some help.

**Comment by CinoNY** [comment]
I had a hell of time to get this to authenticate too. Take a look at this post, it should help you

https://github.com/home-assistant/home-assistant/issues/19189#issuecomment-494970985

**Comment by JamesMcCarthy79** [comment]
> I had a hell of time to get this to authenticate too. Take a look at this post, it should help you
> 
> [home-assistant/home-assistant#19189 (comment)](https://github.com/home-assistant/home-assistant/issues/19189#issuecomment-494970985)

The part I don't understand is the callback url the component points me back to my local http//:[ipaddress] can I change this to my https redirect as the fitbit dev will only allow you to use https as callback address?

**Comment by JamesMcCarthy79** [comment]
I am getting this error

![image](https://user-images.githubusercontent.com/34696670/59380636-e8b37380-8d9c-11e9-9d62-0fdcf08c1d50.png)

**Comment by CinoNY** [comment]
You'll have to use https for the callback. Fitbit made a change to only use https instead of http and that screwed everything up.  I've never seen that error before. Normally I was getting a 500 error. You may have to change the http: component within HA to use https for your local base:

http:
  server_port: 8123
  base_url: https://hassio.something.com

**Comment by choclo** [comment]
Hi @JamesMcCarthy79 were you able to fix this? I already tried using https on the base_url but this is still using http for the callback to fitbit and getting the same issue as you reported (screenshot).

**Comment by JamesMcCarthy79** [comment]
Hi @choclo  I have not managed to fix this yet however I haven't got back to it since June work has been hectic I may have another crack at this tonight. As @SPCulhane suggests the key is in the http/https auth I haven't tried changing my base URL yet as I normally do everything locally I need to see how much I will break in order for this to work.

**Comment by Aygotori** [comment]
any news about a fix?

**Comment by JamesMcCarthy79** [comment]
I have resolved this issue
