### ISSUE TITLE
Integrate New Android TV (Mi Box 4)

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#142]
- [x] Setup Mi Box Tasker MQTT Integration

**Setup Viewing Automations**
- [x] Foxtel - Cartoons
- [x] Foxtel - Sport
- [x] Netflix
- [x] Spotify
- [x] HDHomeRun

**Comment by JamesMcCarthy79** [comment]
Finally got this to work with installing adb tools on my HA host machine then using the native Android TV component
```
apt-get install android-tools-adb
adb connect [device-IP]
```

**Comment by JamesMcCarthy79** [comment]
Next to setup Alexa Voice Commands for all of above plus some frequently used media playlists for spotify and cartoons for Kids.

**Comment by JamesMcCarthy79** [comment]
Done for now will add to this as I play with it

![image](https://user-images.githubusercontent.com/34696670/60872189-9bc99c80-a277-11e9-9043-1e74473f9cac.png)

**Comment by abeksis** [comment]
What are you doing :)

**Comment by AaronArgent** [comment]
Where did you get the androidtv.adb for node-red?

Regards,

Aaron Argent
M: 0408721696
E: AaronArgent@gmail.com

**Comment by AaronArgent** [comment]
Where did you get the androidtv.adb for node-red?

**Comment by AaronArgent** [comment]
Where did you get the androidtv.adb for node-red from?

**Comment by JamesMcCarthy79** [comment]
@abeksis I bought an Android TV Box to try and bring my most used media apps together in one place that could be controlled by HA rather then doing some hacky IR scripts.

**Comment by JamesMcCarthy79** [comment]
@AaronArgent I installed the adb package on my Ubuntu Server which the Android TV component uses to interact with my Android TV. I then simply just use the androidtv.adb_command in a service call node. If you would like to know the specific service calls I use let me know.

**Comment by AaronArgent** [comment]
So your using HA service not a node-red palette 

Am interested in seeing more.  I have Got my Sony bravia android TV working so far, and my Panasonic TV kinda working, but these mi box and Vodafone TVs are causing me alot of headaches.

**Comment by JamesMcCarthy79** [comment]
So I used an app called puffintv for side loading any apps that can't be accessed from the play store. You can use commands on the adb package to see what the installed packages names are I can't remember the command atm if you wan't I can dig this up tonight.

this is what my service call node looks like 

![image](https://user-images.githubusercontent.com/34696670/60935778-5f954b00-a30e-11e9-953c-1de1fa01c22e.png)

**Comment by petrasl1976** [comment]
My MiBOX4 says:
```
root@raspberrypi:/tmp# adb devices
List of devices attached
192.168.88.30:9000	offline
```
I managed to turn on developer mode on devince, but i can't find how to enable **Wireless debugging**. There is no such option as described here https://developer.android.com/studio/command-line/adb

I pick port 9000 as it is the only one which at leaset binds somehow, the other ports do not respond to `adb connect ...` at all. Here are all of them:
```
T0490:~ t0490$ sudo nmap 192.168.88.30
Password:
Starting Nmap 7.91 ( https://nmap.org ) at 2021-04-10 21:55 EEST
Nmap scan report for 192.168.88.30
Host is up (0.0083s latency).
Not shown: 996 closed ports
PORT     STATE SERVICE
8008/tcp open  http
8009/tcp open  ajp13
8443/tcp open  https-alt
9000/tcp open  cslistener
MAC Address: EC:FA:5C:xx:xx:xx (Beijing Xiaomi Electronics)

Nmap done: 1 IP address (1 host up) scanned in 1.69 seconds
T0490:~ t0490$
```

Any ideas how i can connect to it ower the net?
Thanks

**Comment by petrasl1976** [comment]
Just few mins later i found how :) Just need to enable **USB debugging** option and **wifi debugging** will be enabled with the same:
```
PORT     STATE SERVICE
5555/tcp open  freeciv
...
```
and now raspberry see it:
```root@raspberrypi:/tmp# adb devices -l
List of devices attached
192.168.88.30:5555     device product:oneday model:MIBOX4 device:oneday transport_id:3
192.168.88.30:9000     offline transport_id:1
```
