### ISSUE TITLE
Link to Google fit component isn't available

### ISSUE THREAD

**Issue by anatolyra** [JamesMcCarthy79/Home-Assistant-Config#144]
Hey, 

The link to the Google fit component doesn't work: https://github.com/hemantkamalakar/haconfigs/blob/master/custom_components/sensor/google_fit.py

Can you please take a look?

Thanks!

**Comment by JamesMcCarthy79** [comment]
Yes it appears the dev no longer supports this custom_component.

I actually have got a Fitbit and have been merging across to that component but you can find the google custom_component [Here](https://github.com/JamesMcCarthy79/Home-Assistant-Config/tree/master/config/custom_components/google_fit)
