### ISSUE TITLE
Google Fit Integration not working

### ISSUE THREAD

**Issue by polyphia** [JamesMcCarthy79/Home-Assistant-Config#148]
Is google fit integration still working ?

The sensors only showing height and weight on my side and some other users when displayed directly with the custom component .

Perhaps your method of updating fixes this ?

HA version tested : Hassio 0.102

**Comment by JamesMcCarthy79** [comment]
I am not the author of the Google Fit component I have reached out to him but he is no longer supporting this component. I have not touched my HASS for a few months being caught up with working overseas. Let me have a bit of a play this week and see what I can come up with.

**Comment by JamesMcCarthy79** [comment]
If you're interested I got this working again last night.
