### ISSUE TITLE
Error after update 0.106

### ISSUE THREAD

**Issue by NeuzNL** [JamesMcCarthy79/Home-Assistant-Config#151]
Hi,

For some time i tried to use your lay-out and update it to my own settings. A few days ago i had the mini graph working fine but since the update 0.106 i got a error witch i can't fix.

Can you help me with this problem?

Screenshot of the page.
![github Property 0 - Object array](https://user-images.githubusercontent.com/38590565/75595733-e1004000-5a8d-11ea-91a0-fe1eec0a94bc.png)

Thanks 

Neuz_NL

**Comment by JamesMcCarthy79** [comment]
Think this looks related to the mini graph card
