### ISSUE TITLE
Project build smart fridge 

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#19]
Install Rasp pi in fridge with camera and use [machine box](https://github.com/robmarkcole/HASS-Machinebox-Classificationbox) to identify items for shopping list. Automate shopping list send maybe to calendar to collect on way home from work.

Would need to be anal about position of everything in fridge

**Comment by CCOSTAN** [comment]
How would you power the Pi and camera?  I'd be happy being able to grab a snapshot of contents at will when at the grocery store.   (i.e. is there milk in the fridge?)

**Comment by JamesMcCarthy79** [comment]
Maybe a power bank would need to investigate battery life and maybe only take pics twice a day.
Say one pic in the evening as part of the bedtime automation, and another just before I leave work. Would take a bit of training for machinebox as we have about 15 types of milk alone in my house.

**Comment by CCOSTAN** [comment]
Could tie into the foursquare component so if you check into a grocery store, you get a pic sent to you! :)

**Comment by JamesMcCarthy79** [comment]
That would be even better conserve on battery life, I have my shops as one of my zones to trigger a notification to the wives phone I'm there in case she needs to let me know to pick up anything else. I might tie it into this at first to see how accurate it is. I am thinking we would need some lighting also as fridge light wouldn't be on I could build an esp32 to do this with fridge light but prob just easier to put a usb light in the Pi.

**Comment by JamesMcCarthy79** [comment]
Raspberry Pi with camera arrived today will aim to tackle this over the weekend

**Comment by JamesMcCarthy79** [comment]
Camera solution is pretty hit and miss so far, mainly with all the almond/coconut milks can't be seen through for volume status so machine box can't tell empty/full status which is pointless. I don't want to go down the weigh sensor route yet or scan every item in/out fridge. I will wait for Samsung/LG to build a better smart fridge :) shelving this project
