### ISSUE TITLE
Floorplan it's time

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#20]
Time to have a more serious look into floorplan I like the idea of visualising my home to find out from a glance if something is open or on.

**Comment by JamesMcCarthy79** [comment]
I think I will replace this with Lovelace when I get time to work on the screens. I have Lovelace screen ready for bathroom scenes just waiting for renovations to finish

**Comment by CCOSTAN** [comment]
This issue needs pictures. :)

**Comment by JamesMcCarthy79** [comment]
Lovelace is the winner closing this
