### ISSUE TITLE
Create Firmware update scrape sensors

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#21]
I want to be informed through HA of firmware versions for my things.
HA - completed
Sonoff - completed
Ubnt
Mikrotik
Xiaomi
To start with

**Comment by CCOSTAN** [comment]
a generic DOCKER IMAGE update scraper would be awesome too! :)

**Comment by JamesMcCarthy79** [comment]
added podcast

**Comment by CCOSTAN** [comment]
For the podcast, I have a package :  https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/hasspodcast.yaml

Just drop it in and make some quick edits.

**Comment by JamesMcCarthy79** [comment]
@CCOSTAN cheers feedreader a much easier way than what I'm trying to do with scrape comparison

**Comment by JamesMcCarthy79** [comment]
Completed for now

**Comment by JamesMcCarthy79** [comment]
to do add mikrotik routerOS sensor

https://community.home-assistant.io/t/mikrotik-latest-routeros-sensor/60349

**Comment by JamesMcCarthy79** [comment]
Mikrotik Sensor added
