### ISSUE TITLE
Samsung TV power status boolean

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#23]
https://community.home-assistant.io/t/smart-toggle-switch-for-device-using-a-delayed-network-ping-to-detect-power-on-off/52452

**Comment by JamesMcCarthy79** [comment]
Implemented works like a charm

**Comment by CCOSTAN** [comment]
Oh man. You are fast. I have to do this now. :)

**Comment by JamesMcCarthy79** [comment]
It works well, great use case for good night/away routines not to turn on the TV if already off etc
