### ISSUE TITLE
Alarm System

### ISSUE THREAD

**Issue by italianrulez** [JamesMcCarthy79/Home-Assistant-Config#35]
Hello i want to ask how you conect your home assistance to your alarm monitoring company so they can receive your panic alarm. thank you for your great work it is very helpfull

**Comment by JamesMcCarthy79** [comment]
I don't have a conventional alarm system it is all mqtt based using my door/window and motion sensors. For panic mode this used to operate for my old alarm system I have now upgraded to mqtt alarm panel link is in my readme. He is about to update his config to include panic mode with it so follow his progress via the ha link also provided in my readme. I will update this comment as soon as its available if you  plan to use the panel. 

I actually use the UI for panic mode at present what happens is the UI asks for password we put in panic passcode and it turns alarm off but it also runs a script which notifies neighbors and family to call police on our behalf. I haven't included the script as it contains sensitive information. If you want to see an example please visit [here](https://community.home-assistant.io/t/yet-another-take-on-an-alarm-system/32386)
