### ISSUE TITLE
Add Custom Component Tracker

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#51]
https://github.com/custom-components/custom_updater

**Comment by JamesMcCarthy79** [comment]
done 
![image](https://user-images.githubusercontent.com/34696670/46234688-ce766880-c3ba-11e8-80df-b2bc2965e8f7.png)

**Comment by jjanderson** [comment]
Very impressive repo mate,,,, 

 

Get yourself a zwave usb stick and bin the corporate shite,
