### ISSUE TITLE
Problem on configuring alexa echo

### ISSUE THREAD

**Issue by platini76** [JamesMcCarthy79/Home-Assistant-Config#60]
just an info I have problem on configuring alexa echo, I need cloud or there is a method to add it without cloud?

I mean:

alexa_main:
        friendly_name: Alexa Main
        device_class: connectivity
        entity_id: device_tracker.44650df543ec
        value_template: "{{ is_state('device_tracker.44650df543ec', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.44650df543ec', 'home') %}
            mdi:voice
          {% else %}
            mdi:voice
          {% endif %}

I don't find my echo device tracker. sorry for noob question.

**Comment by JamesMcCarthy79** [comment]
The above code only allows you to track if your echo is online or not. To actually add echo so she can voice control your system you need to add the cloud component and then the alexa skill.

Try starting with this https://www.nabucasa.com/config/amazon_alexa/

**Comment by JamesMcCarthy79** [comment]
Just re-open this issue if you need to but its been 26days
