### ISSUE TITLE
Install New Xiaomi Desk Lamp

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#85]
- Install new Lamp 

- setup office desk automations with xiaomi vibration sensor I am still waiting to arrive used as an office chair occupancy sensor :)

**Comment by JamesMcCarthy79** [comment]
@AaronArgent - It is still in the box, I have so many items I haven't found the time to install yet. I'll let you know once I set it up.

**Comment by JamesMcCarthy79** [comment]
Finally Installed this bad boy works really well it is setup in the kids playroom temp until lighting is fixed in there and then it will reside in my under stair study nook and will be automated with the use of an under desk motion sensor and chair vibration sensor.

**Comment by abeksis** [comment]
What installation? :-)

**Comment by JamesMcCarthy79** [comment]
@AaronArgent this lamp works great can light up a whole room or just a small space by just turning the dial, integrates easily with Yeelight component.

@abeksis I do normally include a picture/screenshot my apologies here you go

![image](https://user-images.githubusercontent.com/34696670/59151594-19cc3500-8a79-11e9-9e80-e842d3cb5be8.png)
