### ISSUE TITLE
Xiaomi Plant Sensors Fix

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#90]
Have relocated some plants around and need to connect those to the Pi running MQTT should be in range.

<strike>Front Bougainvillea</strike>
<strike>Lounge Plant</strike>
<strike>Bathroom Plant (Pretty much dead anyways lol)</strike>
- Update Lovelace Cards

**Comment by JamesMcCarthy79** [comment]
Fixed the 2 indoor plants but not sure which plant sensor I used to monitor the plant by the front door need to get the ble sniffer out tonight.

**Comment by JamesMcCarthy79** [comment]
Sorted was locked on to old server but hadn't updated. Moved to new indoor Pi all plants up and running. Just need to finish updates to lovelace cards.

**Comment by jjanderson** [comment]
Lol, i have about 20 of these... tou can always just take it out and see which one is at 0 moisture....

**Comment by JamesMcCarthy79** [comment]
@jjanderson Yeah, I have a Bluetooth scanner which maps out the distances so I can stand right next to it to find its mac.

**Comment by JamesMcCarthy79** [comment]
The end result came up alright

![image](https://user-images.githubusercontent.com/34696670/50663387-34474180-0ff5-11e9-954f-963c0f77b656.png)
