### ISSUE TITLE
Add Holiday/Birthday Automations 🎂 

### ISSUE THREAD

**Issue by JamesMcCarthy79** [JamesMcCarthy79/Home-Assistant-Config#96]

**Comment by auredor** [comment]
maybe an useful component to get public holiday for a given country/state : 
https://www.home-assistant.io/components/binary_sensor.workday/

or directly using github code in node-red : 
https://github.com/dr-prodigy/python-holidays#available-countries

**Comment by JamesMcCarthy79** [comment]
@auredor something like this

https://github.com/JamesMcCarthy79/Home-Assistant-Config/blob/master/config/json_data/days.json I just need to find the time to get some reminders in node red

**Comment by JamesMcCarthy79** [comment]
@auredor something like this

https://github.com/JamesMcCarthy79/Home-Assistant-Config/blob/master/config/json_data/days.json I just need to find the time to get some reminders in node red
