### ISSUE TITLE
trash_recycle package - sesnors.yaml file

### ISSUE THREAD

**Issue by Pre10der** [JamesMcCarthy79/Home-Assistant-Config#99]
@JamesMcCarthy79  - Your doco for the trash_recycle files refers to your sensors.yaml file, but it is not in your repo. Can you share the relevant portions for the date & time sensors please?

Thanks!

**Comment by JamesMcCarthy79** [comment]
@Pre10der Apologies I am in the middle of rewriting all of my README as you can appreciate I am maintaining alot lol, I reached this package yet you can find the related package for those sensors now located in the date_time package. I have updated the package README to reflect this change.

Thanks James

**Comment by JamesMcCarthy79** [comment]
@Pre10der - I have added them back into the package for you.

**Comment by Pre10der** [comment]
Thanks James. All sorted and much appreciated.

--
Ian Gregory | Enterprise Architect
CEnet - Catholic Education Network
L5, 111-113 Crown St, Wollongong NSW 2500
E: ian.gregory@cenet.catholic.edu.au
Ph. +61 2 4222 9308

________________________________
